// Mocks generated by Mockito 5.4.2 from annotations
// in weather/test/features/feature_weather/presentation/bloc/weather_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather/core/params/forecast_params.dart' as _i7;
import 'package:weather/core/recources/data_state.dart' as _i3;
import 'package:weather/features/feature_weather/domain/entities/current_weather_entity.dart'
    as _i9;
import 'package:weather/features/feature_weather/domain/entities/forecast_entity.dart'
    as _i6;
import 'package:weather/features/feature_weather/domain/repository/weather_repository.dart'
    as _i2;
import 'package:weather/features/feature_weather/domain/usecases/get_forecast_usecase.dart'
    as _i4;
import 'package:weather/features/feature_weather/domain/usecases/get_weather_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherRepository_0 extends _i1.SmartFake
    implements _i2.WeatherRepository {
  _FakeWeatherRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_1<T> extends _i1.SmartFake implements _i3.DataState<T> {
  _FakeDataState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetForecastUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetForecastUseCase extends _i1.Mock
    implements _i4.GetForecastUseCase {
  MockGetForecastUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherRepository get weatherRepository => (super.noSuchMethod(
        Invocation.getter(#weatherRepository),
        returnValue: _FakeWeatherRepository_0(
          this,
          Invocation.getter(#weatherRepository),
        ),
      ) as _i2.WeatherRepository);
  @override
  _i5.Future<_i3.DataState<_i6.ForecastEntity>> call(
          _i7.ForecastParams? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<_i3.DataState<_i6.ForecastEntity>>.value(
            _FakeDataState_1<_i6.ForecastEntity>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i6.ForecastEntity>>);
}

/// A class which mocks [GetWeatherUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherUseCase extends _i1.Mock implements _i8.GetWeatherUseCase {
  MockGetWeatherUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherRepository get weatherRepository => (super.noSuchMethod(
        Invocation.getter(#weatherRepository),
        returnValue: _FakeWeatherRepository_0(
          this,
          Invocation.getter(#weatherRepository),
        ),
      ) as _i2.WeatherRepository);
  @override
  _i5.Future<_i3.DataState<_i9.CurrentWeatherEntity>> call(String? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<_i3.DataState<_i9.CurrentWeatherEntity>>.value(
            _FakeDataState_1<_i9.CurrentWeatherEntity>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i9.CurrentWeatherEntity>>);
}
